const editor=document.querySelector('#editor');
const fileInput=document.querySelector('#fileInput');
const dropZone=document.querySelector('#dropZone');
const frame=document.querySelector('#previewFrame');
const textPreview=document.querySelector('#textPreview');
const embedOutput=document.querySelector('#embedOutput');
const fileBadge=document.querySelector('#fileBadge');
const typeBadge=document.querySelector('#typeBadge');
const STORAGE_KEY='ubg-content';

const demo=`<!doctype html><html><head><style>body{margin:0;display:grid;place-items:center;min-height:100vh;background:#111827;color:white;font-family:Arial}.card{padding:28px;border-radius:18px;background:#1e293b;text-align:center}button{padding:10px 16px;border:0;border-radius:10px;background:#7c8dff;color:white;font-weight:bold}</style></head><body><div class="card"><h1>UBG Demo</h1><p id="score">Score: 0</p><button onclick="score++ ; document.querySelector('#score').textContent='Score: '+score">Add point</button></div><script>let score=0<\/script></body></html>`;

function isJson(value){try{JSON.parse(value);return true}catch{return false}}
function detect(value){const text=value.trim();if(!text)return'text';if(/<\/?[a-z][\s\S]*>/i.test(text))return'html';if(isJson(text))return'json';if(/(^|\n)\s*[^{}]+\{[\s\S]*:\s*[^;]+;?/m.test(text))return'css';if(/\b(const|let|var|function|return|document|window)\b|=>/.test(text))return'javascript';return'text'}
function escape(value){return value.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function documentFor(value,type){if(type==='html')return value;if(type==='json'||type==='text')return`<!doctype html><body style="margin:0;padding:24px;background:#0f172a;color:#e2e8f0;font:15px monospace"><pre style="white-space:pre-wrap">${escape(value)}</pre></body>`;if(type==='css')return`<!doctype html><style>${value}</style><body style="font:18px Arial;padding:30px"><h2>CSS preview</h2><div class="sample">Sample element</div></body>`;return`<!doctype html><body style="margin:0;padding:24px;background:#0f172a;color:#e2e8f0;font:16px Arial"><h2>JavaScript preview</h2><pre id="output"></pre><script>document.querySelector('#output').textContent=${JSON.stringify(value)}<\/script></body>`}
function render(){const value=editor.value;const type=detect(value);typeBadge.textContent=type;frame.srcdoc=documentFor(value,type);textPreview.textContent=value;if(value.trim()){frame.classList.remove('hidden');textPreview.classList.add('hidden')}else{frame.classList.add('hidden');textPreview.classList.remove('hidden');textPreview.textContent='Paste code or upload a file to preview it.'}const encoded=documentFor(value,type).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');embedOutput.value=`<iframe title="UBG embed" srcdoc="${encoded}" style="width:100%;height:520px;border:0"></iframe>`;localStorage.setItem(STORAGE_KEY,JSON.stringify({content:value,name:fileBadge.textContent}))}
function readFile(file){if(!file)return;fileBadge.textContent=file.name;file.text().then(value=>{editor.value=value;render()}).catch(()=>{editor.value='Unable to read this file.';render()})}
editor.addEventListener('input',render);fileInput.addEventListener('change',e=>{readFile(e.target.files[0]);fileInput.value='' });
['dragenter','dragover'].forEach(name=>dropZone.addEventListener(name,e=>{e.preventDefault();dropZone.classList.add('dragging')}));['dragleave','drop'].forEach(name=>dropZone.addEventListener(name,e=>{e.preventDefault();dropZone.classList.remove('dragging')}));dropZone.addEventListener('drop',e=>readFile(e.dataTransfer.files[0]));
document.querySelector('#loadDemo').addEventListener('click',()=>{editor.value=demo;fileBadge.textContent='demo.html';render()});document.querySelector('#clearBtn').addEventListener('click',()=>{editor.value='';fileBadge.textContent='untitled.txt';render()});document.querySelector('#downloadBtn').addEventListener('click',()=>{const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([editor.value],{type:'text/plain'}));link.download=fileBadge.textContent||'ubg-export.txt';link.click()});document.querySelector('#copyEmbed').addEventListener('click',async()=>{await navigator.clipboard.writeText(embedOutput.value);const button=document.querySelector('#copyEmbed');button.textContent='Copied!';setTimeout(()=>button.textContent='Copy embed',1200)});
try{const saved=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');if(saved?.content){editor.value=saved.content;fileBadge.textContent=saved.name||'saved.txt'}else{editor.value=demo;fileBadge.textContent='demo.html'}}catch{editor.value=demo;fileBadge.textContent='demo.html'}render();
